require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

 platform :ios, '11.0'

target 'GL' do
  config = use_native_modules!

  use_unimodules!

  use_react_native!(:path => config["reactNativePath"])

  target 'GLTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'GL-tvOS' do
  # Pods for GL-tvOS

  target 'GL-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
